repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/koalaman/shellcheck
    rev: v0.9.0
    hooks:
      - id: shellcheck
        args: [--severity=warning]

  - repo: https://github.com/mvdan/sh
    rev: v3.7.1
    hooks:
      - id: shfmt
        args: [-i, 2, -ci]
repos:
- repo: https://github.com/scop/pre-commit-shfmt
  rev: v3.12.0-2
  hooks: [{id: shfmt, args: ["-i","2","-ci","-sr"]}]
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.11.0.1
  hooks: [{id: shellcheck, args: ["-x"]}]
