repos:
- repo: https://github.com/scop/pre-commit-shfmt
  rev: v3.10.0-1
  hooks: [{id: shfmt, args: ["-i","2","-ci","-sr"]}]
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.10.0.1
  hooks: [{id: shellcheck, args: ["-x"]}]
