site_name: "E-Waste Workshop — Wiki"
repo_name: "Forgejo"
repo_url: "http://localhost:3000/eww-admin/eww"

theme:
  name: material
  features:
    - navigation.instant
    - content.code.copy

plugins:
  - search
  # - awesome-pages
  # - git-revision-date-localized

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Strona główna: index.md
  - Przewodnik:
      - Wprowadzenie: guide/intro.md
  - Wiki:
      - Index: wiki/index.md
      - Obsidian: wiki/obsidian.md
      - Neovim:   wiki/neovim.md
      - Kubuntu:  wiki/kubuntu.md
  - Vendor: vendor.md
  - Dev/Prod:
      - Endpointy: ENDPOINTS.md
