repos:
- repo: https://github.com/scop/pre-commit-shfmt
  rev: v3.7.0
  hooks:
  - id: shfmt
- repo: https://github.com/caarlos0/shellcheck-precommit
  rev: v2.12.0
  hooks:
  - id: shellcheck
- repo: https://github.com/adrienverge/yamllint
  rev: v1.35.1
  hooks:
  - id: yamllint
    args: [ -c, tools/yamllint.yml ]
- repo: https://github.com/ansible/ansible-lint
  rev: v24.9.2
  hooks:
  - id: ansible-lint
