site_name: E-Waste Workshop â€” Wiki
site_dir: site
theme:
  name: material
  features: [content.code.copy, navigation.sections]
nav:
  - Start: docs/index.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
